require 'initializer/controls/proof'
require 'initializer/controls/attributes'
require 'initializer/controls/initialized'
require 'initializer/controls/visibility'
require 'initializer/controls/default_values'
